# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24ef82538d8bd9488f3c4e404d0b625f0324fc81d5db711745893cf1fd34f68a52cf60248bafcaa6467b6e37afdc389eda64727635c6de6ac2eb881f70d65750

test:
  secret_key_base: f0bc74ca654a1fa2c0f7acf6c7595c364e32d04116e43b218db74106b12c39a7ef494056bd31dd73bb8c4d52970f62106431bf4e02c44b44a12ebbe4de27b26a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
